language: ruby
rvm:
  - 2.2.2
env:
  - DB=postgresql
sudo: false
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database registry_test;' -U postgres
  - psql -c 'create database registry_whois_test;' -U postgres
  - psql -c 'create database registry_api_log_test;' -U postgres
  - "bundle install --without=staging development production"
  - cp config/application-example.yml config/application.yml
  - cp config/secrets-example.yml config/secrets.yml
  - cp config/database-travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:all:drop
  - RAILS_ENV=test bundle exec rake db:all:setup
script:
  - RAILS_ENV=test bundle exec rake
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
notifications:
  email:
    - artur.beljajev@internet.ee
branches:
  only:
    - staging
